
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMAYORMENORIGUALDIFERENTEMAYORIGUALMENORIGUALleftANDORleftMASMENOSleftPORDIVIDIDOAND COMA DIFERENTE DIVIDIDO IDENTIFICADOR IGUAL MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS NUMERO OR PARDER PARIZQ PORexpresion : expresion_aritmetica\n                 | expresion_logicaexpresion_aritmetica : termino\n                            | expresion_aritmetica MAS termino\n                            | expresion_aritmetica MENOS terminotermino : factor\n              | termino POR factor\n              | termino DIVIDIDO factorfactor : NUMERO\n              | IDENTIFICADOR\n              | PARIZQ expresion_aritmetica PARDERexpresion_logica : termino_logico\n                       | expresion_logica AND termino_logico\n                       | expresion_logica OR termino_logicotermino_logico : expresion_aritmetica IGUAL expresion_aritmetica\n                     | expresion_aritmetica DIFERENTE expresion_aritmetica\n                     | expresion_aritmetica MAYOR expresion_aritmetica\n                     | expresion_aritmetica MENOR expresion_aritmetica\n                     | expresion_aritmetica MAYORIGUAL expresion_aritmetica\n                     | expresion_aritmetica MENORIGUAL expresion_aritmetica'
    
_lr_action_items = {'NUMERO':([0,9,10,11,12,13,14,15,16,17,18,19,20,21,],[7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'IDENTIFICADOR':([0,9,10,11,12,13,14,15,16,17,18,19,20,21,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'PARIZQ':([0,9,10,11,12,13,14,15,16,17,18,19,20,21,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,6,7,8,23,24,25,26,27,28,29,30,31,33,34,35,36,],[0,-1,-2,-3,-12,-6,-9,-10,-4,-5,-15,-16,-17,-18,-19,-20,-13,-14,-7,-8,-11,]),'MAS':([2,4,6,7,8,22,23,24,25,26,27,28,29,30,32,34,35,36,],[10,-3,-6,-9,-10,10,-4,-5,10,10,10,10,10,10,10,-7,-8,-11,]),'MENOS':([2,4,6,7,8,22,23,24,25,26,27,28,29,30,32,34,35,36,],[11,-3,-6,-9,-10,11,-4,-5,11,11,11,11,11,11,11,-7,-8,-11,]),'IGUAL':([2,4,6,7,8,23,24,32,34,35,36,],[12,-3,-6,-9,-10,-4,-5,12,-7,-8,-11,]),'DIFERENTE':([2,4,6,7,8,23,24,32,34,35,36,],[13,-3,-6,-9,-10,-4,-5,13,-7,-8,-11,]),'MAYOR':([2,4,6,7,8,23,24,32,34,35,36,],[14,-3,-6,-9,-10,-4,-5,14,-7,-8,-11,]),'MENOR':([2,4,6,7,8,23,24,32,34,35,36,],[15,-3,-6,-9,-10,-4,-5,15,-7,-8,-11,]),'MAYORIGUAL':([2,4,6,7,8,23,24,32,34,35,36,],[16,-3,-6,-9,-10,-4,-5,16,-7,-8,-11,]),'MENORIGUAL':([2,4,6,7,8,23,24,32,34,35,36,],[17,-3,-6,-9,-10,-4,-5,17,-7,-8,-11,]),'AND':([3,4,5,6,7,8,23,24,25,26,27,28,29,30,31,33,34,35,36,],[18,-3,-12,-6,-9,-10,-4,-5,-15,-16,-17,-18,-19,-20,-13,-14,-7,-8,-11,]),'OR':([3,4,5,6,7,8,23,24,25,26,27,28,29,30,31,33,34,35,36,],[19,-3,-12,-6,-9,-10,-4,-5,-15,-16,-17,-18,-19,-20,-13,-14,-7,-8,-11,]),'PARDER':([4,6,7,8,22,23,24,34,35,36,],[-3,-6,-9,-10,36,-4,-5,-7,-8,-11,]),'POR':([4,6,7,8,23,24,34,35,36,],[20,-6,-9,-10,20,20,-7,-8,-11,]),'DIVIDIDO':([4,6,7,8,23,24,34,35,36,],[21,-6,-9,-10,21,21,-7,-8,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expresion':([0,],[1,]),'expresion_aritmetica':([0,9,12,13,14,15,16,17,18,19,],[2,22,25,26,27,28,29,30,32,32,]),'expresion_logica':([0,],[3,]),'termino':([0,9,10,11,12,13,14,15,16,17,18,19,],[4,4,23,24,4,4,4,4,4,4,4,4,]),'termino_logico':([0,18,19,],[5,31,33,]),'factor':([0,9,10,11,12,13,14,15,16,17,18,19,20,21,],[6,6,6,6,6,6,6,6,6,6,6,6,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expresion","S'",1,None,None,None),
  ('expresion -> expresion_aritmetica','expresion',1,'p_expresion','parser.py',15),
  ('expresion -> expresion_logica','expresion',1,'p_expresion','parser.py',16),
  ('expresion_aritmetica -> termino','expresion_aritmetica',1,'p_expresion_aritmetica','parser.py',20),
  ('expresion_aritmetica -> expresion_aritmetica MAS termino','expresion_aritmetica',3,'p_expresion_aritmetica','parser.py',21),
  ('expresion_aritmetica -> expresion_aritmetica MENOS termino','expresion_aritmetica',3,'p_expresion_aritmetica','parser.py',22),
  ('termino -> factor','termino',1,'p_termino','parser.py',31),
  ('termino -> termino POR factor','termino',3,'p_termino','parser.py',32),
  ('termino -> termino DIVIDIDO factor','termino',3,'p_termino','parser.py',33),
  ('factor -> NUMERO','factor',1,'p_factor','parser.py',42),
  ('factor -> IDENTIFICADOR','factor',1,'p_factor','parser.py',43),
  ('factor -> PARIZQ expresion_aritmetica PARDER','factor',3,'p_factor','parser.py',44),
  ('expresion_logica -> termino_logico','expresion_logica',1,'p_expresion_logica','parser.py',51),
  ('expresion_logica -> expresion_logica AND termino_logico','expresion_logica',3,'p_expresion_logica','parser.py',52),
  ('expresion_logica -> expresion_logica OR termino_logico','expresion_logica',3,'p_expresion_logica','parser.py',53),
  ('termino_logico -> expresion_aritmetica IGUAL expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',62),
  ('termino_logico -> expresion_aritmetica DIFERENTE expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',63),
  ('termino_logico -> expresion_aritmetica MAYOR expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',64),
  ('termino_logico -> expresion_aritmetica MENOR expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',65),
  ('termino_logico -> expresion_aritmetica MAYORIGUAL expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',66),
  ('termino_logico -> expresion_aritmetica MENORIGUAL expresion_aritmetica','termino_logico',3,'p_termino_logico','parser.py',67),
]
